### ISSUE TITLE
Location 

### ISSUE THREAD

**Issue by iTanui** [HAHAYOUDEAD/FoodsByCalorieWaltz#1]
Hey! I can help you translate your mod to polish if you want. I messing with your localization file to make one for myself, but if you want me to I can send you this file to share this to others.

**Comment by HAHAYOUDEAD** [comment]
Hey! I didn't get the notification for your issue for some reason, sorry. Sure you can send it over, I'll include it for the next update. You can make a pull request here, or find me over at TLD modding discord (Waltz#4178)
