### ISSUE TITLE
Incompatability with Camping Tools

### ISSUE THREAD

**Issue by bushtail** [HAHAYOUDEAD/FoodsByCalorieWaltz#10]
UpdateCaloriesInPrefab is throwing an NPE when this mod is installed.

**Comment by HAHAYOUDEAD** [comment]
it throws NRE whenever something else makes Modcomponent error, it's been like this since forever and unless something changed in MC - there is no incompatibility, likely just incorrect installation of some other MC mod

**Comment by HAHAYOUDEAD** [comment]
oh whoops it's a month old issue 😅

**Comment by bushtail** [comment]
> it throws NRE whenever something else makes Modcomponent error, it's been like this since forever and unless something changed in MC - there is no incompatibility, likely just incorrect installation of some other MC mod

half a year later i see this, it's really good to know what actually causes it. learning experiences
