### ISSUE TITLE
Lore pieces spawn with Hunting knife attached to them in Interloper

### ISSUE THREAD

**Issue by onebunchmugen** [HAHAYOUDEAD/FoodsByCalorieWaltz#12]
Hunting knives and hatchets dont spawn in  interloper. You have to craft them all. Thats the point of interloper difficulty. However I found a letter from waltz employee with a knife stuck on it at Lighthouse of desolation point. This is just a minor inconvinience though. Not an issue but immersion breaking oversight. :D I guess if i disable lore, knives would be gone too

**Comment by onebunchmugen** [comment]
I would love read that guys story in interloper getting loot.

**Comment by HAHAYOUDEAD** [comment]
removed with latest release
