### ISSUE TITLE
I was wondering if this mod could be translated into Korean

### ISSUE THREAD

**Issue by ysk6684** [HAHAYOUDEAD/FoodsByCalorieWaltz#14]
I tried to translate this mod personally, but it was difficult and I couldn't find a way, so I gave up. Is there any chance you could translate this mod into Korean?

**Comment by HAHAYOUDEAD** [comment]
I.. don't know Korean 😅 It is already translated into Japanese, so unicode set is not a problem. Just grab the localization.json and add Korean lines to it, should work. Localization file is inside the .modcomponent, and .modcomponent is just renamed .zip, so you can open it with any archiver

**Comment by ysk6684** [comment]
oh my god ! brilliant thank !!!
