### ISSUE TITLE
Nuts in Honey

### ISSUE THREAD

**Issue by hozz1235** [HAHAYOUDEAD/FoodsByCalorieWaltz#2]
Hello. First of all, THANK YOU for all the work you've done on mods!!
Just now, I consumed some 100% condition Nuts in Honey and received food poisoning. Is this normal?

**Comment by HAHAYOUDEAD** [comment]
Hey. I don't get notifications for issues for some reason, so you better ask me on discord in the future. 

Yeah it's normal, you can disable this behavior in settings though. 

The reason for that being a thing is that honey produces more calories than anything else in the game, so I wanted to implement some kind of disadvantage to eating a whole jar. Eating it once won't cause any problems, each other consumption increases risk of getting food poisoning though. You can lower the risk by drinking hot teas between consumtions. Timer resets every 8 ingame hours iirc. This supposed to simulate irl honey indigestion (when you eat TOO much of it)
