### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by Kin-Tal** [HAHAYOUDEAD/FoodsByCalorieWaltz#3]
When I break branches or do any other time-consuming activity outside, processor is loaded by 100%, from which the FPS drops from 60 to 15.
P.S. What's your Discord? И можно ли обращаться по-русски, ибо в английском я не силён?

**Comment by HAHAYOUDEAD** [comment]
Пока что не представляю как мой мод мог на это повлиять, но разберусь. Спасибо за репорт

**Comment by Kin-Tal** [comment]
Может каждый продукт в ядро запросы на состояния посылает как-то не так?... Ладно, не буду гадать. Спасибо что отреагировали!

**Comment by Kin-Tal** [comment]
> Пока что не представляю как мой мод мог на это повлиять, но разберусь. Спасибо за репорт

Я проверил. Без других модов ВСЁ РАВНО есть просадка. Но с 60ти до 25-30ти. Всё равно ощутимая. Тоесть таки проблема есть у мода с процессором. Вопрос конечно остаётся, какой конфликт модов вызывает просадку аж в четыре раза. Могу поискать, если надо.

**Comment by HAHAYOUDEAD** [comment]
я нашел причину, исправил и смотрю чтоб больше ничего не сломалось. Если интересно, проблема была с проверкой на достаточное освещение для выполнения действия  Я добавил к проверке свои свечки точно так же как это делает Hinterland, но видимо моды работают немного иначе и это сильно нагружает систему
