### ISSUE TITLE
NANNA'S OATS cause crash

### ISSUE THREAD

**Issue by HeiNaiBaiMao** [HAHAYOUDEAD/FoodsByCalorieWaltz#8]
i like your mod but some it make my game crash.
![螢幕擷取畫面 (15)](https://github.com/HAHAYOUDEAD/FoodsByCalorieWaltz/assets/147289943/85c52d97-e836-4641-a8f3-f0903aa14b2a)
[2023-10-08 10-30-45.zip](https://github.com/HAHAYOUDEAD/FoodsByCalorieWaltz/files/12839618/2023-10-08.10-30-45.zip)

**Comment by HAHAYOUDEAD** [comment]
hey, sorry for late reply. Can you join our modding discord and upload your log in #troubleshooting there? Bot will check if everything is up to date. You can ping me there (@Waltz) so I can take a look: https://discord.gg/x3aynBJX

**Comment by waltz** [comment]
sup
